sudo: required
services:
- docker

before_script:
- git clone https://github.com/konrads/fake-aws.git
- export PATH=$PATH:$PWD/fake-aws/bin
- data-gen dev resources/aws-template resources/aws-stage
- fake-aws refresh containers resources/aws-stage
- cp conf/private.conf.travis conf/private.conf

language: scala
scala:
- 2.11.7

# presence of following is required by AWS libraries, but they're not actually used
env:
- AWS_ACCESS_KEY_ID=bogus_access_key AWS_SECRET_KEY=bogus_access_key
