sudo: required
services:
- docker

before_script:
- git clone https://github.com/konrads/fake-aws.git
- export PATH=$PATH:$PWD/fake-aws/bin
- data-gen dev resources/aws-template resources/aws-stage
- fake-aws refresh containers resources/aws-stage

language: scala
scala:
- 2.11.7
