sudo: required
services:
- docker

before_script:
- echo using TRAVIS_SCALA_VERSION: $TRAVIS_SCALA_VERSION
- git clone https://github.com/konrads/fake-aws.git
- export PATH=$PATH:$PWD/fake-aws/bin
- data-gen dev resources/aws-template resources/aws-stage
- fake-aws refresh containers resources/aws-stage
- cp conf/private.localhost.conf conf/private.conf

language: scala
scala:
- 2.11.6
- 2.11.7
